FROM golang:1.27-alpine

WORKDIR /app

# Install dependencies for hot reload
RUN go install github.com/air-verse/air@v1.67.4

# Install migrate tool
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1

# Install golangci-lint
RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.13.2

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

# Use air for hot reload during development
CMD ["air", "-c", ".air.toml"]
